language: node_js
node_js:
  - 10
  - 12
  - 13
script:
  - yarn test
  - yarn inspect
  - yarn build
deploy:
  provider: npm
  email: info@onfido.com
  api_key:
    secure: Xu1KIsBoMvlWJ1met18JhXJFsOK/AdDBv2jrFF+i4sA99RfBwXKpbAy7UC0XyHVfCVfXzhYkA6Is+eFtHphgAqEiM/p2qkIRknQlxGIbXVDzTsnL5L6zHM7rDML+tjO5Oq1QFiB3qDKFLK5S4OgSiPb/And+NgBYbCbvIWOvnyPKTQZ9+txmy+9L2mrOZ0muofvuk4t/v2/b8mlx23PgElZPXoQFvhDGRF7li1jB2y/s0tB59MAt/FPFOzYJa2G6LjtZZEUSS93752/VpDjmzoByJhg0SYr76+XhbDXrIoWmGOv3WK15K0FXMOZujKeTcnRZYY1GR0W1QihLGsFs1DhaP7EGgICkpyLeruF/n67Zl2IpkY1suWEP0eULCNTW3ZilV7cRfRxptNNTTN3HE53VIUNPOsKs80xjDI52qM/H0lftC+2jTN+aRE3B1XsOkcd5ZUgm5feC/c28eJ+CLc7D/Wf4ByvBWHFvLiGIIItp22GM/2FVLECOFKP12zQ8BXKFnycBF8ucKkgNgVJfSoiPc6I7HxA1xk/ilZ6E2TL5ZejlkC2qDfISWKlCL89kgR/2nkhTFEgth+RF18GHjsfg9bvmBiubVejTFFbcVieubLQKUoYCdM8hY3ApWR/eUR/RoWFQC4iDlS0QwhNG+kP4CmCNGJpP3tWBVyRpSqs=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: '13'
